---
- name: postgreSQL
  apt:
    name: postgresql
    state: present
  become: yes

- name: postgresql-client
  apt:
    name: postgresql-client
    state: present
  become: yes

- name: enable postgreSQL
  systemd:
    state: started
    name: postgresql
    enabled: yes
